In [1]:
import pandas as pd
import numpy as np

In [8]:
pkd = pd.read_csv("pkd.csv", sep=";", encoding='utf8')

pkd.head()

,id,kolejnosc,symbol,nazwa,opis,dataKoncaObowiazywania,dataPoczatkuObowiazywania,elementNadrzednyId,elementNadrzednyUuid,uuid,...,opisNieobejmuje,opisObejmuje,opisObejmujeNieobejmuje,opisObejmujeTakze,przeszleZdarzenia,uwagi,wygenerowany,zmianyOdPoprzedniejWersji,znakZmianCn,numerPoziomu
0,26177,1,A,"ROLNICTWO, LEŚNICTWO, ŁOWIECTWO I RYBACTWO",NaN,NaN,NaN,0,NaN,73529589-3B43-4C24-AEEC-472EE616DE0A,...,NaN,NaN,<body><h2>SEKCJA A</h2><p>Sekcja ta obejmuje d...,NaN,NaN,NaN,NaN,NaN,NaN,1
1,26178,2,01,"UPRAWY ROLNE, CHÓW I HODOWLA ZWIERZĄT, ŁOWIECT...",NaN,NaN,NaN,0,73529589-3B43-4C24-AEEC-472EE616DE0A,EA3BA8CE-481B-4B8E-AEE0-8CBB3732F9D9,...,NaN,NaN,<body><h2>01</h2><p>Dział ten obejmuje: </p><u...,NaN,NaN,NaN,NaN,NaN,NaN,2
2,26179,3,01.1,Uprawy rolne inne niż wieloletnie,NaN,NaN,NaN,0,EA3BA8CE-481B-4B8E-AEE0-8CBB3732F9D9,5FBA5907-DB56-4FA4-B712-D14BAA176F9F,...,NaN,NaN,<body><h2>01.1</h2><p>Grupa ta obejmuje uprawy...,NaN,NaN,NaN,NaN,NaN,NaN,3
3,26180,4,01.11,"Uprawa zbóż, roślin strączkowych i roślin olei...",NaN,NaN,NaN,0,5FBA5907-DB56-4FA4-B712-D14BAA176F9F,6669922A-0C8B-4985-8095-DBD6E437D3AE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,26181,5,01.11.Z,"Uprawa zbóż, roślin strączkowych i roślin olei...",NaN,NaN,NaN,0,6669922A-0C8B-4985-8095-DBD6E437D3AE,2364E423-C97E-4941-8EE5-FFBE262018D8,...,NaN,NaN,<body><h2>01.11.Z</h2><p>Podklasa ta obejmuje ...,NaN,NaN,NaN,NaN,NaN,NaN,5

In [9]:
pkd = pkd[['symbol', 'nazwa']]

pkd.head()

    symbol                                              nazwa
0        A         ROLNICTWO, LEŚNICTWO, ŁOWIECTWO I RYBACTWO
1       01  UPRAWY ROLNE, CHÓW I HODOWLA ZWIERZĄT, ŁOWIECT...
2     01.1                 Uprawy rolne inne niż wieloletnie
3    01.11  Uprawa zbóż, roślin strączkowych i roślin olei...
4  01.11.Z  Uprawa zbóż, roślin strączkowych i roślin olei...

In [10]:
pkd['typ'] = \
    np.where(pkd.symbol.str.match(r'^[A-Z]+$'),
             'PKDMainSection', \
             np.where(pkd.symbol.str.match(r'^[0-9]+$'),
                      'PKDMainDivision', \
                      np.where(pkd.symbol.str.match(r'^[0-9]+.[0-9]$'),
                               'PKDMainGroup', \
                               'PKDMainClass')
                      ))

pkd.head()

    symbol                                              nazwa              typ
0        A         ROLNICTWO, LEŚNICTWO, ŁOWIECTWO I RYBACTWO   PKDMainSection
1       01  UPRAWY ROLNE, CHÓW I HODOWLA ZWIERZĄT, ŁOWIECT...  PKDMainDivision
2     01.1                 Uprawy rolne inne niż wieloletnie      PKDMainGroup
3    01.11  Uprawa zbóż, roślin strączkowych i roślin olei...     PKDMainClass
4  01.11.Z  Uprawa zbóż, roślin strączkowych i roślin olei...     PKDMainClass

In [11]:
pkd = pkd[pkd['typ'].isin(['PKDMainSection', 'PKDMainDivision'])]

pkd.head()

   symbol                                              nazwa              typ
0       A         ROLNICTWO, LEŚNICTWO, ŁOWIECTWO I RYBACTWO   PKDMainSection
1      01  UPRAWY ROLNE, CHÓW I HODOWLA ZWIERZĄT, ŁOWIECT...  PKDMainDivision
71     02                    LEŚNICTWO I POZYSKIWANIE DREWNA  PKDMainDivision
84     03                                           RYBACTWO  PKDMainDivision
95      B                            GÓRNICTWO I WYDOBYWANIE   PKDMainSection

In [12]:
pkd['symbol'] = pkd.symbol.str.replace(r'^0+', '').str.replace(r'\.', '')

pkd.head()

   symbol                                              nazwa              typ
0       A         ROLNICTWO, LEŚNICTWO, ŁOWIECTWO I RYBACTWO   PKDMainSection
1       1  UPRAWY ROLNE, CHÓW I HODOWLA ZWIERZĄT, ŁOWIECT...  PKDMainDivision
71      2                    LEŚNICTWO I POZYSKIWANIE DREWNA  PKDMainDivision
84      3                                           RYBACTWO  PKDMainDivision
95      B                            GÓRNICTWO I WYDOBYWANIE   PKDMainSection

In [15]:
pkd.to_csv("pkd_data.csv", index=False, encoding='utf8')